version: "3.9"
services:
  api-node:
    image: api
    container_name: api-container
    build:
      context: ./api-node/
      dockerfile: ../.docker/Dockerfile
      target: dev
    init: true
    volumes:
      - type: bind
        source: ./api-node/
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules
      - type: volume
        target: /usr/src/app/dist
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    ports:
      - 3000:3000
    networks:
      - backend 
    restart: unless-stopped
  db:
    env_file:
      - ./.docker/config.env.dev
    image: mysql:5.7
    container_name: mysql-container
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - backend
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
networks:
  backend: